export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const STORE_USER_DETAILS = 'STORE_USER_DETAILS';

export const STORE_INVENTORIES = 'STORE_INVENTORIES';
export const REMOVE_FROM_INVENTORIES = 'REMOVE_FROM_INVENTORIES';
export const ADD_TO_INVENTORIES = 'ADD_TO_INVENTORIES';

export const STORE_SALES = 'STORE_SALES';
export const REMOVE_FROM_SALES = 'REMOVE_FROM_SALES';
export const ADD_TO_SALES = 'ADD_TO_SALES';

export const STORE_EXPENSES = 'STORE_EXPENSES';
export const REMOVE_FROM_EXPENSES = 'REMOVE_FROM_EXPENSES';
export const ADD_TO_EXPENSES = 'ADD_TO_EXPENSES';

export const STORE_PAYOUTS = 'STORE_PAYOUTS';
export const REMOVE_FROM_PAYOUTS = 'REMOVE_FROM_PAYOUTS';
export const ADD_TO_PAYOUTS = 'ADD_TO_PAYOUTS';

export const STORE_BANKS = 'STORE_BANKS';
export const REMOVE_FROM_BANKS = 'REMOVE_FROM_BANKS';
export const ADD_TO_BANKS = 'ADD_TO_BANKS';

export const STORE_SHOPS = 'STORE_SHOPS';
export const REMOVE_FROM_SHOPS = 'REMOVE_FROM_SHOPS';
export const ADD_TO_SHOPS = 'ADD_TO_SHOPS';
export const SET_SELECTED_SHOP = 'SET_SELECTED_SHOP';
